/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Demo
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
@SpringBootApplication
class App {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {

            SpringApplication.run(App::class.java, *args)
        }
    }
}
